### ISSUE TITLE
Is the map in the dom file working!?

### ISSUE THREAD

**Issue by Walidmash** [facg3/msn-AutoComplete#13]
https://github.com/facg3/msn-AutoComplete/blob/8c372d2136eec1a1ef9a7ffdb6da271cd51ef2f3/public/dom.js#L29

Here is a good example of using google maps in web projects
https://developers.google.com/maps/documentation/javascript/examples/map-geolocation

**Comment by Salam-Dalloul** [comment]
it's working now :D
